[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
upload_speed = 921600
monitor_speed = 115200
board_upload.flash_size = 2MB
lib_deps =
    https://github.com/DaveGamble/cJSON.git
