#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_IDENTITY "YOUR_WIFI_IDENTITY"
#define WIFI_USERNAME "YOUR_WIFI_USERNAME"
#define WIFI_PASS "YOUR_WIFI_PASSWORD"

#define DHT11_GPIO 4

#define TELEMETRY_BASE_URL "http://YOUR_SERVER_IP_OR_DOMAIN"
#define HEALTH_URL TELEMETRY_BASE_URL "/health"
#define TELEMETRY_URL TELEMETRY_BASE_URL "/telemetry"
#define DEVICE_ID "ID_FOR_THIS_DEVICE"
